---
format: 
  dashboard:
    orientation: columns
    expandable: true
    theme: 
      - cosmo
server: shiny
include-before-body:
  text: |
    <style>
      #quarto-dashboard-header {
        display: none;
      }
    </style>
---

```{r}
#| context: setup
library(shiny)
library(ggplot2)
library(deeptime)
library(palaeoverse)
# Custom functions
source("utils.R")
```

```{r data}
#| context: data
df <- readRDS("data/PBDB.RDS")
# Get bins
bins <- readRDS("data/stages.RDS")
```

# {.sidebar}

### Analyses

```{r}
radioButtons("type", "Type",
             c(Sampling = "sampling", Range = "range", 
               Diversity = "richness", Diversification = "rates"))
radioButtons("rank", "Taxonomic rank",
             c(Species = "species", Genus = "genus", Family = "family"), selected = "genus")
selectInput("group", "Group by",
            c(None = ".", Family = "family", Genus = "genus", Country = "cc"))
```

### Filter

```{r}
selectInput("region", "Geographic region",
            c("Global", "Caribbean", "Mediterranean", 
              "Arabia", "Indo-Australian Archipelago"), 
              selected = "Caribbean")
selectInput("family", "Family",
            c(All = ".", sort(unique(df$family))),
            selected = "All")
```

# Plot

```{r}
plotOutput('plot')
```

```{r}
#| context: server

plot_data <- reactive({
  # Filter data
  df <- df |>
    filter_region(region = input$region) |>
    filter_rank(rank = input$rank) |>
    filter_family(fam = input$family)
  if (input$type == "range") {
    get_temporal_ranges(df, name = input$rank, group = input$group)
  }
})
 
output$plot <- renderPlot({
  plot_data()
})
```